### ISSUE TITLE
Can't add namespaced packages

### ISSUE THREAD

**Issue by 0xR** [StarRatio/star-ratio#29]
![image](https://cloud.githubusercontent.com/assets/6420016/24072219/e1eb4fc4-0be3-11e7-998c-d23838b740ae.png)

I think this is the best way to check the popularity of "just angular" (> v2). However it doesn't seem to work. I wonder what I'm looking at when I click the frontend frameworks link.

**Comment by dmitry-zaets** [comment]
Thanks for the reporting.
Fixed that bug! But with @angular/core there is a problem because from some reason it doesn't have the number of downloads, even on the npm website: https://www.npmjs.com/package/@angular/core
