### ISSUE TITLE
npm downloads gets NaN when npm link not informed

### ISSUE THREAD

**Issue by davidpelayo** [StarRatio/star-ratio#5]
Tested with StarRatio/star-ratio repo.

<img width="857" alt="nan" src="https://cloud.githubusercontent.com/assets/84540/18313531/d137ebd4-74d4-11e6-9092-a164bc62c1ec.png">

**Comment by dmitry-zaets** [comment]
Server should return null in downloads can't be calculated.
Component should show `-` in case if value is not present.
